#!/usr/bin/env bash
# shellcheck disable=1090

export PYENV_ROOT="$HOME/.pyenv"
export N_PREFIX="$HOME/n"

if [[ -d "$N_PREFIX/bin" ]]; then
    export PATH="$N_PREFIX/bin:$PATH"
fi

if [[ -d "$PYENV_ROOT/bin" ]]; then
    export PATH="$PYENV_ROOT/bin:$PATH"
fi

if [[ -d "$HOME/.local/bin" ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d "$HOME/.basher/bin" ]]; then
    export PATH="$HOME/.basher/bin:$PATH"
fi

if [[ -d "$HOME/bin" ]]; then
    export PATH="$HOME/bin:$PATH"
fi

for file in "$(dirname "${BASH_SOURCE[0]}")"/*.sh; do
    source "$file"
done
unset file

if hash pyenv 2>/dev/null; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

if hash basher 2>/dev/null; then
    eval "$(basher init -)"
fi

alias nodejs="node"

__exit_code_color() {
    local EXITCODE=$?
    if [ $EXITCODE == 0 ]; then
        printf "\e[0;32m"
    else
        printf "\e[0;31m"
    fi
}

export VIRTUAL_ENV_DISABLE_PROMPT=1

PS1='\r\n\[\e[0;33m\] \w \r\n\[$(__exit_code_color)\]\$ \[\e[0m\]'

export PS1
